[project]
name = "particles"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "circle-fit>=0.2.1",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "opencv-python>=4.13.0.92",
    "scikit-image>=0.26.0",
    "typer>=0.26.6",
]
